name: CMake-Wasm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Wasm_Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Git Submodules
        run: git submodule update --init --recursive

      - name: Ccache Setup
        uses: hendrikmuhs/ccache-action@v1.2.9
        with:
          key: wasm-Release
          variant: sccache

      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.43

      - name: Configure CMake with Emscripten SDK
        run: emcmake cmake cgfx -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_EMSCRIPTEN=ON -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build
        run:
          emmake make -C ${{github.workspace}}/build -j2

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Wasm_Release
          path: |
            build/**/*.exe
            build/**/*.html
            build/**/*.js
            build/**/*.wasm
            build/**/*.data
            build/**/EngineResources
            build/**/EditorResources
            build/**/GameResources
            !build/**/CMakeFiles